### ISSUE TITLE
Filter should apply to annotation playback

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/project-client#17]
When a filter is applied to annotations, only the filtered annotations should playback -- for example if the listener only wants to hear the sections by a particular speaker.

**Comment by SteveMarvin** [comment]
I notice in the filtered playback issue that although the audio cuts out once the spanned clip is complete, the player continues to run to the end of the entire clip, just with no sound. Is this as desired?

Or should it end playback?

However, the feature works as described. Approved!
