### ISSUE TITLE
Layout issue with audio player and filter component

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/project-client#33]
The player component runs past the frame, and the search and filter components are also pushed too far to the right. This is from the [Another Test project](https://avannotate.github.io/another-test/events/7afefd55-4797-48bd-9b26-2279f0aa796b/).

<img width="1378" alt="Screenshot 2024-09-30 at 9 10 07 AM" src="https://github.com/user-attachments/assets/2b890c17-f56b-42ea-ae57-21e60de6a380">

**Comment by camdendotlol** [comment]
I think I fixed this in my set filtering PR. Didn't realize it was an issue outside of that branch.

**Comment by camdendotlol** [comment]
@SteveMarvin I'm moving this to Review/QA without a PR attached because I think it was fixed in another PR. Feel free to move back to the backlog if not.

**Comment by SteveMarvin** [comment]
Looks good!
