### ISSUE TITLE
The burger menu should include the index

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/project-client#66]
<img width="633" alt="Screenshot 2024-10-17 at 3 18 26 PM" src="https://github.com/user-attachments/assets/e21c77b8-cb6e-4701-babc-8dd6e529631b">

**Comment by SteveMarvin** [comment]
Selected page bolding in the hamburger menu is erratic. Some pages get it and some do not.
![image](https://github.com/user-attachments/assets/1e23c96f-83a1-4f08-8b00-34330a5e6bf4)

![image](https://github.com/user-attachments/assets/3ad19773-99b1-4d37-9ac8-86d2b1d59c92)
