### ISSUE TITLE
Event Comparison formatting issues

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/project-client#85]
- [ ] Buttons wrap when the screen is resized. Can we push the buttons to the next line instead of wrapping the text in them?
<img width="982" alt="Screenshot 2024-11-05 at 1 46 23 PM" src="https://github.com/user-attachments/assets/25b5d74c-1981-4f5c-a3f7-258f7f693b5b">

- [ ] When one Event in an Event Comparison has a title that wraps and the other doesn't, videos get misaligned. Should match the line height of the longer title.

<img width="1151" alt="Screenshot 2024-10-28 at 12 58 46 PM" src="https://github.com/user-attachments/assets/aeadc8fb-ca6e-4ce5-b813-c2f0f8af17a6">

**Comment by camdendotlol** [comment]
Can I have a link to the GH repo for the project in the first screenshot?

**Comment by absempere** [comment]
@camdendotlol This happens to buttons on all projects when you resize the window. See: https://avannotate.github.io/dev-demo/pages/clips-of-different-types/ and resize. Repo here: https://github.com/AVAnnotate/dev-demo

First project is here: https://saamturner.github.io/leslie-flint/ and repo: https://github.com/saamturner/leslieflint
